version: '3'
services:
  spark:
    container_name: "spark"
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"
    volumes:
      - ./work:/home/jovyan/work/
    command: bash -c "start.sh jupyter lab --LabApp.token=''"


#docker run -p 8888:8888 --name pyspark4 -v "$PWD":/home/jovyan/work  jupyter/pyspark-notebook  start.sh jupyter lab --LabApp.token=''